# Generated by Django 5.1 on 2024-09-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Epi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_epi', models.CharField(max_length=100)),
                ('descricao_epi', models.TextField()),
                ('quantidade_total', models.IntegerField()),
                ('quantidade_disponivel', models.IntegerField()),
            ],
        ),
    ]
