# Generated by Django 5.1 on 2024-09-24 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_cadastroEPI', '0001_initial'),
        ('app_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(auto_now_add=True)),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('epi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cadastroEPI.epi')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_usuarios.usuario')),
            ],
        ),
    ]
