# Generated by Django 5.1 on 2024-09-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='quantidade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
