# Generated by Django 5.1 on 2024-09-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0002_alter_usuario_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('admin', 'Admin'), ('colaborador', 'Colaborador'), ('sem_acesso', 'Sem acesso')], default='colaborador', max_length=15),
        ),
    ]
